
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:13 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:13 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe 
      Build flags: /DWIN32;/D_WINDOWS;/W3;/MD;/O2;/Ob2;/DNDEBUG
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.8.5+b5265ef37 for .NET Framework
      Build started 2024-03-05 11:14:39 PM.
      
      Project "C:\\Users\\Jay\\Documents\\Github\\HarvestEye\\openMVG Built\\arrow\\src\\arrow_cpp-build\\src\\xsimd_ep-build\\CMakeFiles\\3.28.1\\CompilerIdC\\CompilerIdC.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
        Creating directory "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        Touching "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\Jay\\Documents\\Github\\HarvestEye\\openMVG Built\\arrow\\src\\arrow_cpp-build\\src\\xsimd_ep-build\\CMakeFiles\\3.28.1\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Done Building Project "C:\\Users\\Jay\\Documents\\Github\\HarvestEye\\openMVG Built\\arrow\\src\\arrow_cpp-build\\src\\xsimd_ep-build\\CMakeFiles\\3.28.1\\CompilerIdC\\CompilerIdC.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:01.14
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/Jay/Documents/Github/HarvestEye/openMVG Built/arrow/src/arrow_cpp-build/src/xsimd_ep-build/CMakeFiles/3.28.1/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:13 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe 
      Build flags: /DWIN32;/D_WINDOWS;/GR;/EHsc;/D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING;/MD;/O2;/Ob2;/DNDEBUG
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.8.5+b5265ef37 for .NET Framework
      Build started 2024-03-05 11:14:41 PM.
      
      Project "C:\\Users\\Jay\\Documents\\Github\\HarvestEye\\openMVG Built\\arrow\\src\\arrow_cpp-build\\src\\xsimd_ep-build\\CMakeFiles\\3.28.1\\CompilerIdCXX\\CompilerIdCXX.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
        Creating directory "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        Touching "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\Jay\\Documents\\Github\\HarvestEye\\openMVG Built\\arrow\\src\\arrow_cpp-build\\src\\xsimd_ep-build\\CMakeFiles\\3.28.1\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Done Building Project "C:\\Users\\Jay\\Documents\\Github\\HarvestEye\\openMVG Built\\arrow\\src\\arrow_cpp-build\\src\\xsimd_ep-build\\CMakeFiles\\3.28.1\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:01.87
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/Jay/Documents/Github/HarvestEye/openMVG Built/arrow/src/arrow_cpp-build/src/xsimd_ep-build/CMakeFiles/3.28.1/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:13 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/Jay/Documents/Github/HarvestEye/openMVG Built/arrow/src/arrow_cpp-build/src/xsimd_ep-build/CMakeFiles/CMakeScratch/TryCompile-8u3rb7"
      binary: "C:/Users/Jay/Documents/Github/HarvestEye/openMVG Built/arrow/src/arrow_cpp-build/src/xsimd_ep-build/CMakeFiles/CMakeScratch/TryCompile-8u3rb7"
    cmakeVariables:
      CMAKE_C_FLAGS: " /DWIN32 /D_WINDOWS /W3  /MD /O2 /Ob2 /DNDEBUG"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Jay/Documents/Github/HarvestEye/openMVG Built/arrow/src/arrow_cpp-build/src/xsimd_ep-build/CMakeFiles/CMakeScratch/TryCompile-8u3rb7'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_212e6.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.8.5+b5265ef37 for .NET Framework
        Build started 2024-03-05 11:14:44 PM.
        
        Project "C:\\Users\\Jay\\Documents\\Github\\HarvestEye\\openMVG Built\\arrow\\src\\arrow_cpp-build\\src\\xsimd_ep-build\\CMakeFiles\\CMakeScratch\\TryCompile-8u3rb7\\cmTC_212e6.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_212e6.dir\\Debug\\".
          Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
          Creating directory "C:\\Users\\Jay\\Documents\\Github\\HarvestEye\\openMVG Built\\arrow\\src\\arrow_cpp-build\\src\\xsimd_ep-build\\CMakeFiles\\CMakeScratch\\TryCompile-8u3rb7\\Debug\\".
          Creating directory "cmTC_212e6.dir\\Debug\\cmTC_212e6.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_212e6.dir\\Debug\\cmTC_212e6.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
          Touching "cmTC_212e6.dir\\Debug\\cmTC_212e6.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D NDEBUG /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_212e6.dir\\Debug\\\\" /Fd"cmTC_212e6.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.38.33134 for x64
          Copyright (C) Microsoft Corporation.  All rights reserved.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D NDEBUG /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_212e6.dir\\Debug\\\\" /Fd"cmTC_212e6.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          CMakeCCompilerABI.c
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\Jay\\Documents\\Github\\HarvestEye\\openMVG Built\\arrow\\src\\arrow_cpp-build\\src\\xsimd_ep-build\\CMakeFiles\\CMakeScratch\\TryCompile-8u3rb7\\Debug\\cmTC_212e6.exe" /INCREMENTAL /ILK:"cmTC_212e6.dir\\Debug\\cmTC_212e6.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/Jay/Documents/Github/HarvestEye/openMVG Built/arrow/src/arrow_cpp-build/src/xsimd_ep-build/CMakeFiles/CMakeScratch/TryCompile-8u3rb7/Debug/cmTC_212e6.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/Jay/Documents/Github/HarvestEye/openMVG Built/arrow/src/arrow_cpp-build/src/xsimd_ep-build/CMakeFiles/CMakeScratch/TryCompile-8u3rb7/Debug/cmTC_212e6.lib" /MACHINE:X64  /machine:x64 cmTC_212e6.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_212e6.vcxproj -> C:\\Users\\Jay\\Documents\\Github\\HarvestEye\\openMVG Built\\arrow\\src\\arrow_cpp-build\\src\\xsimd_ep-build\\CMakeFiles\\CMakeScratch\\TryCompile-8u3rb7\\Debug\\cmTC_212e6.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_212e6.dir\\Debug\\cmTC_212e6.tlog\\unsuccessfulbuild".
          Touching "cmTC_212e6.dir\\Debug\\cmTC_212e6.tlog\\cmTC_212e6.lastbuildstate".
        Done Building Project "C:\\Users\\Jay\\Documents\\Github\\HarvestEye\\openMVG Built\\arrow\\src\\arrow_cpp-build\\src\\xsimd_ep-build\\CMakeFiles\\CMakeScratch\\TryCompile-8u3rb7\\cmTC_212e6.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:02.62
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:13 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/Jay/Documents/Github/HarvestEye/openMVG Built/arrow/src/arrow_cpp-build/src/xsimd_ep-build/CMakeFiles/CMakeScratch/TryCompile-evur3p"
      binary: "C:/Users/Jay/Documents/Github/HarvestEye/openMVG Built/arrow/src/arrow_cpp-build/src/xsimd_ep-build/CMakeFiles/CMakeScratch/TryCompile-evur3p"
    cmakeVariables:
      CMAKE_CXX_FLAGS: " /DWIN32 /D_WINDOWS  /GR /EHsc /D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING  /MD /O2 /Ob2 /DNDEBUG"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Jay/Documents/Github/HarvestEye/openMVG Built/arrow/src/arrow_cpp-build/src/xsimd_ep-build/CMakeFiles/CMakeScratch/TryCompile-evur3p'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_3990a.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.8.5+b5265ef37 for .NET Framework
        Build started 2024-03-05 11:14:47 PM.
        
        Project "C:\\Users\\Jay\\Documents\\Github\\HarvestEye\\openMVG Built\\arrow\\src\\arrow_cpp-build\\src\\xsimd_ep-build\\CMakeFiles\\CMakeScratch\\TryCompile-evur3p\\cmTC_3990a.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_3990a.dir\\Debug\\".
          Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
          Creating directory "C:\\Users\\Jay\\Documents\\Github\\HarvestEye\\openMVG Built\\arrow\\src\\arrow_cpp-build\\src\\xsimd_ep-build\\CMakeFiles\\CMakeScratch\\TryCompile-evur3p\\Debug\\".
          Creating directory "cmTC_3990a.dir\\Debug\\cmTC_3990a.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_3990a.dir\\Debug\\cmTC_3990a.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
          Touching "cmTC_3990a.dir\\Debug\\cmTC_3990a.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D _SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING /D NDEBUG /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_3990a.dir\\Debug\\\\" /Fd"cmTC_3990a.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.38.33134 for x64
          Copyright (C) Microsoft Corporation.  All rights reserved.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D _SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING /D NDEBUG /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_3990a.dir\\Debug\\\\" /Fd"cmTC_3990a.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          CMakeCXXCompilerABI.cpp
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\Jay\\Documents\\Github\\HarvestEye\\openMVG Built\\arrow\\src\\arrow_cpp-build\\src\\xsimd_ep-build\\CMakeFiles\\CMakeScratch\\TryCompile-evur3p\\Debug\\cmTC_3990a.exe" /INCREMENTAL /ILK:"cmTC_3990a.dir\\Debug\\cmTC_3990a.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/Jay/Documents/Github/HarvestEye/openMVG Built/arrow/src/arrow_cpp-build/src/xsimd_ep-build/CMakeFiles/CMakeScratch/TryCompile-evur3p/Debug/cmTC_3990a.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/Jay/Documents/Github/HarvestEye/openMVG Built/arrow/src/arrow_cpp-build/src/xsimd_ep-build/CMakeFiles/CMakeScratch/TryCompile-evur3p/Debug/cmTC_3990a.lib" /MACHINE:X64  /machine:x64 cmTC_3990a.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_3990a.vcxproj -> C:\\Users\\Jay\\Documents\\Github\\HarvestEye\\openMVG Built\\arrow\\src\\arrow_cpp-build\\src\\xsimd_ep-build\\CMakeFiles\\CMakeScratch\\TryCompile-evur3p\\Debug\\cmTC_3990a.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_3990a.dir\\Debug\\cmTC_3990a.tlog\\unsuccessfulbuild".
          Touching "cmTC_3990a.dir\\Debug\\cmTC_3990a.tlog\\cmTC_3990a.lastbuildstate".
        Done Building Project "C:\\Users\\Jay\\Documents\\Github\\HarvestEye\\openMVG Built\\arrow\\src\\arrow_cpp-build\\src\\xsimd_ep-build\\CMakeFiles\\CMakeScratch\\TryCompile-evur3p\\cmTC_3990a.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:01.90
        
      exitCode: 0
...
